import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'screens/welcome_screen.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by the Firebase CLI
import 'screens/login_screen.dart';
import 'screens/loading_screen.dart';
import 'screens/register_screen.dart';
import 'screens/market_screen.dart';
import 'screens/buy_screen.dart';
import 'screens/fruit_screen.dart';
import 'screens/veggies_grain_screen.dart';
import 'screens/learning_screen.dart';
import 'screens/cart_model.dart';
import '../providers/article_provider.dart';
import 'screens/homepage_screen.dart';
import 'providers/produce_provider.dart';
import 'screens/sell_screen.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (context) => CartModel()),
        ChangeNotifierProvider(create: (context) => ArticleProvider()),
        ChangeNotifierProvider(create: (_) => ProduceProvider()),
      ],
      child: const FarmBoostApp(),
    ),
  );
}

class FarmBoostApp extends StatelessWidget {
  const FarmBoostApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FARMarket',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.white12),
        useMaterial3: true,
        primarySwatch: Colors.green,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      debugShowCheckedModeBanner: false,
      initialRoute: '/',
      routes: {
        '/': (context) => const LoadingScreen(),
        '/login': (context) => const LoginScreen(),
        '/register': (context) => RegisterScreen(),
        '/home': (context) => const WelcomeScreen(),
        '/market': (context) => const MarketScreen(),
        '/buy': (context) => const BuyScreen(),
        '/fruit': (context) => const FruitScreen(),
        '/other': (context) => const VeggiesGrainsScreen(),
        '/learn': (context) => const LearnAndGrowScreen(),
        '/homepage': (context) => const HomePage(),
        '/sell': (context) => const SalesPage(),
      },
    );
  }
}
